### ISSUE TITLE
'alig_one' referenced before assignement

### ISSUE THREAD

**Issue by felixlinker** [mk36fyvy/multivitamin#7]
Got the following trace:
```
(gbn1920_chrifero-QA35qt9W) PS C:\Users\felix\git\gbn\gbn1920_chrifero\benchmarks> python .\benchmark.py -l multivitamin -i ..\..\multivitamin\graph_examples\Chem\acetylsalicylic_acid.graph ..\..\multivitamin\graph_examples\Chem\benzene.graph
Reading ..\..\multivitamin\graph_examples\Chem\acetylsalicylic_acid.graph from Michel K.
Successfully parsed ..\..\multivitamin\graph_examples\Chem\acetylsalicylic_acid.graph

Reading ..\..\multivitamin\graph_examples\Chem\benzene.graph from Michel K.
Successfully parsed ..\..\multivitamin\graph_examples\Chem\benzene.graph

Traceback (most recent call last):
  File ".\benchmark.py", line 21, in <module>
    duration = timeit.timeit(globals=globals(), **libraries[args.library])
  File "C:\Program Files\Python37\Lib\timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "C:\Program Files\Python37\Lib\timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "C:\Users\felix\git\gbn\gbn1920_chrifero\benchmarks\bm_multivitamin.py", line 18, in run
    return aligner.multalign()
  File "c:\users\felix\git\gbn\multivitamin\multivitamin\utils\multalign.py", line 65, in multalign
    self.greedy()
  File "c:\users\felix\git\gbn\multivitamin\multivitamin\utils\multalign.py", line 107, in greedy
    self.graph_list.remove(alig_one)
UnboundLocalError: local variable 'alig_one' referenced before assignment
```

**Comment by mk36fyvy** [comment]
Error is fixed. The parser was not correctly assigning unique IDs, because the filename was incorrectly parsed from the path-string.

4d6219b20eca65c3cbfcb4e8709926f64b182070
