### ISSUE TITLE
'NoneType' is not subscriptable

### ISSUE THREAD

**Issue by felixlinker** [mk36fyvy/multivitamin#9]
#7 was fixed appropriately, however I now get:
```
(gbn1920_chrifero-QA35qt9W) PS C:\Users\felix\git\gbn\gbn1920_chrifero\benchmarks> python .\benchmark.py -l multivitamin -i ..\..\multivitamin\graph_examples\Chem\acetylsalicylic_acid.graph ..\..\multivitamin\graph_examples\Chem\benzene.graph
Reading ..\..\multivitamin\graph_examples\Chem\acetylsalicylic_acid.graph from Michel K.
Successfully parsed acetylsalicylic_acid

Reading ..\..\multivitamin\graph_examples\Chem\benzene.graph from Michel K.
Successfully parsed benzene

Traceback (most recent call last):
  File ".\benchmark.py", line 17, in <module>
    duration = timeit.timeit(globals=globals(), **libraries[args.library])
  File "C:\Program Files\Python37\Lib\timeit.py", line 232, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "C:\Program Files\Python37\Lib\timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "C:\Users\felix\git\gbn\gbn1920_chrifero\benchmarks\bm_multivitamin.py", line 18, in run
    return aligner.multalign()
  File "c:\users\felix\git\gbn\multivitamin\multivitamin\utils\multalign.py", line 65, in multalign
    self.greedy()
  File "c:\users\felix\git\gbn\multivitamin\multivitamin\utils\multalign.py", line 92, in greedy
    max_alignment = self.apply_algorithm( g1, g2 )[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mk36fyvy** [comment]
It is quite hard to think into the issue without being able to reproduce it.

Although you told me, you were not using the default values for the flags, I suppose you indicated the algorithm correctly (subVF2), right? You can take a look into the default values in [https://github.com/mk36fyvy/multivitamin/blob/master/multivitamin/utils/flags.py](url)

If you don't find the error there, we will need to dig deeper into what you do differently in bm_multalign.py

**Comment by felixlinker** [comment]
Fixed. My algorithm argument was wrong because it was in lowercase.
